# Generated by Django 5.1.6 on 2025-02-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_history_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='history',
            field=models.TextField(),
        ),
    ]
